services:
  bird:
    # image: registry.internal/bird:latest
    build:
      context: ./docker
      target: runtime
      # args:
      #   BIRD_VERSION: "<BIRD_VERSION>"
    volumes:
      - ./config:/etc/bird:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/sbin/birdc", "-s", "/run/bird/bird.ctl", "show", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
