log stderr all;
timeformat protocol iso long;
debug protocols all;
cli "/run/bird/bird.ctl";

router id 192.0.2.1;

protocol device test_device {
    scan time 10;
}

protocol static test_static_device {
    ipv4;
    route 198.51.100.0/24 via "eth0";
}

protocol static test_static_blackhole {
    ipv4;
    route 198.51.100.0/24 blackhole;
}

protocol direct test_direct {
    ipv4;
    # ipv6;
    # interface "*";
    interface "lo";
    interface "eth0";
}
